name: draft_annotation
description: Annotations for the draft package
version: 0.0.1
repository: https://github.com/josiahsrc/draft

environment:
  sdk: ^3.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
