name: draft
description: Immer, but for dart. Convert between immutable and mutable objects.
version: 0.0.2
repository: https://github.com/josiahsrc/draft

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ">=7.0.0 <8.0.0"
  build: ^2.3.1
  source_gen: ^2.0.0
  draft_annotation: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_test: ^2.2.3
  build_runner: ^2.4.15
