name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  draft_annotation:
    path: ../../draft_annotation

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner:
  draft:
    path: ../

dependency_overrides:
  draft_annotation:
    path: ../../draft_annotation
  draft:
    path: ../
